import numpy as np
import cvxpy as cp
import os
import csv


# ---------------------------------------------------------------------------
# 1. Price Data Builder
# ---------------------------------------------------------------------------
def build_price_vectors(T):
    da_prices_24 = np.array([
        0.04, 0.03, 0.03, 0.02, 0.03, 0.05,
        0.07, 0.09, 0.08, 0.06, 0.05, 0.05,
        0.04, 0.04, 0.05, 0.06, 0.08, 0.11,
        0.12, 0.10, 0.08, 0.07, 0.05, 0.04
    ])
    da_prices = np.repeat(da_prices_24, T // 24)
    
    # Direct settlement prices ($/kWh)
    # Upward activation: Net rate earned per kWh of reduced load / increased discharge
    p_up_net = da_prices * 1.45  
    
    # Downward activation: Net rate paid per kWh of extra energy consumed
    p_dn_net = da_prices * 0.55  
    
    return da_prices, p_up_net, p_dn_net


# ---------------------------------------------------------------------------
# 2. Activation Profile Generators & External Data Loaders
# ---------------------------------------------------------------------------
def generate_upward_activation_profiles(N_up, T, dt=0.2):
    """
    Generates N_up time-series upward activation profiles (N_up x T).
    - Upward Bids: 1% off-peak base up to 7% peak cap.
    - Persistence: 80% once activated.
    """
    hours = np.linspace(0, 24 - dt, T)
    morning_peak = np.exp(-0.5 * ((hours - 9.5) / 1.5) ** 2)
    evening_peak = np.exp(-0.5 * ((hours - 21.0) / 1.2) ** 2)
    peak_profile = morning_peak + evening_peak
    
    p_01_up = 0.00 + 0.0 * peak_profile  # Upward: 1% -> 7%
    p_10 = 0.20                           # 80% persistence rate
    
    delta_up = np.zeros((N_up, T))
    
    np.random.seed(42)
    for n in range(N_up):
        for t in range(T):
            if t == 0:
                delta_up[n, t] = 1.0 if np.random.rand() < p_01_up[0] else 0.0
            else:
                if delta_up[n, t-1] == 0:
                    delta_up[n, t] = 1.0 if np.random.rand() < p_01_up[t] else 0.0
                else:
                    delta_up[n, t] = 0.0 if np.random.rand() < p_10 else 1.0
                    
    return delta_up


def load_external_downward_scenarios(data_folder="copula_scenarios"):
    """
    Loads the downward offer probability scenarios and weights generated by BID_external.
    Default directory: 'copula_scenarios'
    """
    weights_path = os.path.join(data_folder, "weights.npy")
    zonal_scenarios_path = os.path.join(data_folder, "zonal_down_scenarios_mw.npy")
    
    if not os.path.exists(weights_path) or not os.path.exists(zonal_scenarios_path):
        raise FileNotFoundError(
            f"External scenario files missing in '{data_folder}/'. "
            f"Please run the BID_external pipeline script first."
        )

    weights = np.load(weights_path)                       # Shape: (S,)
    zonal_down_scenarios_mw = np.load(zonal_scenarios_path) # Shape: (S, T)
    
    # Convert zonal capacity/probabilities into binary activation indicators (S x T)
    delta_dn_st = (zonal_down_scenarios_mw > 0).astype(float)
    
    return delta_dn_st, weights


# ---------------------------------------------------------------------------
# 3. Polytope Data Loader (MODIFIED TO LOAD POLYTOPE PROBABILITIES)
# ---------------------------------------------------------------------------
def load_scenario_polytopes(input_root="reduced_fleet_scenarios"):
    """
    Loads scenario polytopes and their associated probability weights (pi_k).
    """
    L_inv = np.load(os.path.join(input_root, "L_inv.npy"))
    scenario_dirs = sorted([
        d for d in os.listdir(input_root)
        if d.startswith("scenario_") and os.path.isdir(os.path.join(input_root, d))
    ])
    if not scenario_dirs:
        raise FileNotFoundError(f"No scenario sub-directories found in '{input_root}'.")

    scenarios = []
    num_scenarios = len(scenario_dirs)
    
    for sd in scenario_dirs:
        path = os.path.join(input_root, sd)
        prob_path = os.path.join(path, "probability.npy")
        
        # Load associated scenario probability if present, else fallback to uniform weight
        if os.path.exists(prob_path):
            prob = float(np.load(prob_path))
        else:
            prob = 1.0 / num_scenarios
            
        scenarios.append({
            "name"             : sd,
            "gamma_agg_diag_x" : np.load(os.path.join(path, "gamma_agg_diag_x.npy")),
            "gamma_agg_x"      : np.load(os.path.join(path, "gamma_agg_x.npy")),
            "h_0"              : np.load(os.path.join(path, "h_0.npy")),
            "probability"      : prob
        })
        
    # Ensure loaded scenario probabilities sum up to 1.0
    total_prob = sum(sc["probability"] for sc in scenarios)
    if not np.isclose(total_prob, 1.0):
        for sc in scenarios:
            sc["probability"] /= total_prob

    return scenarios, L_inv


# ---------------------------------------------------------------------------
# 4. Main Optimization Engine (CVaR-Constrained Stochastic Formulation)
# ---------------------------------------------------------------------------
def solve_expected_cost_bidder(
    input_root      : str   = "reduced_fleet_scenarios",
    down_data_folder: str   = "copula_scenarios",
    output_dir      : str   = "copula_bids",
    T               : int   = 96,
    C_slack         : float = 0.25,
    M               : float = 450.0,
    dt              : float = 0.2,
    H               : int   = 8,       # Minimum run-time block length
    min_bid_kw      : float = 0.0,
    alpha           : float = 0.95,    # CVaR confidence level
    cvar_max        : float = 50.0,    # Maximum allowable CVaR limit on slacks
    time_limit_sec  : float = 200.0    # Solver cutoff limit
):
    # 1. Load External Downward Scenarios from BID_external
    delta_dn_st, scenario_weights = load_external_downward_scenarios(down_data_folder)
    S = len(scenario_weights)  # S scenarios

    print(f"\n{'='*85}")
    print(f"  CVAR-CONSTRAINED STOCHASTIC BIDDER (SLACK RISK)")
    print(f"  [S={S} Downward Scenarios | Alpha={alpha} | CVaR Max Slack={cvar_max}]")
    print(f"{'='*85}\n")

    # Load polytopes and associated probabilities (pi_k)
    scenarios, L_inv = load_scenario_polytopes(input_root)
    K = len(scenarios)
    
    print("Loaded Polytope Scenarios & Probabilities:")
    for k, sc in enumerate(scenarios):
        print(f"  - Polytope Scenario {k} ('{sc['name']}'): Probability pi_{k} = {sc['probability']:.4f}")
    print("-" * 85)

    # 2. Generate Upward Activation Profiles
    delta_up_st = generate_upward_activation_profiles(S, T, dt)
    da_prices, p_up_net, p_dn_net = build_price_vectors(T)

    I_T     = np.eye(T)
    H_tilde = np.vstack([I_T, -I_T, L_inv, -L_inv])

    # First-stage decision variables (Bids)
    p_DA   = cp.Variable(T, name="p_DA")        
    r_up   = cp.Variable(T, name="r_up")        
    r_down = cp.Variable(T, name="r_down")     
    
    u_up       = cp.Variable(T, boolean=True, name="u_up")       
    v_up_start = cp.Variable(T, boolean=True, name="v_up_start") 
    v_up_end   = cp.Variable(T, boolean=True, name="v_up_end")   
    
    u_dn       = cp.Variable(T, boolean=True, name="u_dn")       
    v_dn_start = cp.Variable(T, boolean=True, name="v_dn_start") 
    v_dn_end   = cp.Variable(T, boolean=True, name="v_dn_end")   

    # Second-stage recourse variables (Dimensions: K x S x T)
    p_ch    = cp.Variable((K, S, T), name="p_ch")
    s_plus  = cp.Variable((K, S, T), name="s_plus",  nonneg=True)
    s_minus = cp.Variable((K, S, T), name="s_minus", nonneg=True)
    x_0     = cp.Variable((K, S, T), name="x_0")

    # CVaR Variables for Slack Variable Risk
    zeta_slack = cp.Variable(name="VaR_zeta_slack")
    psi_slack  = cp.Variable((K, S), nonneg=True, name="tail_loss_psi_slack")

    constraints = [
        p_DA >= 0.0,
        r_up <= p_DA,
        p_DA + r_down <= M,
    ]

    # Commitment Logic & Minimum Run-Time Block Length (H)
    for t in range(T):
        if t == 0:
            constraints.append(u_up[t] == v_up_start[t])
            constraints.append(u_dn[t] == v_dn_start[t])
        else:
            constraints.append(u_up[t] - u_up[t-1] == v_up_start[t] - v_up_end[t])
            constraints.append(u_dn[t] - u_dn[t-1] == v_dn_start[t] - v_dn_end[t])

        constraints.append(v_up_start[t] + v_up_end[t] <= 1)
        constraints.append(v_dn_start[t] + v_dn_end[t] <= 1)
        constraints.append(u_up[t] + u_dn[t] <= 1)

        constraints.append(r_up[t] >= min_bid_kw * u_up[t])
        constraints.append(r_up[t] <= M * u_up[t])
        constraints.append(r_down[t] >= min_bid_kw * u_dn[t])
        constraints.append(r_down[t] <= M * u_dn[t])

        look_ahead = min(t + H, T)
        for k_h in range(t, look_ahead):
            constraints.append(u_up[k_h] >= v_up_start[t])
            constraints.append(u_dn[k_h] >= v_dn_start[t])

        if t < T - 1:
            is_transition_up = v_up_start[t+1] + v_up_end[t+1]
            is_transition_dn = v_dn_start[t+1] + v_dn_end[t+1]
            constraints.extend([
                r_up[t] - r_up[t+1] <= M * is_transition_up,
                r_up[t+1] - r_up[t] <= M * is_transition_up,
                r_down[t] - r_down[t+1] <= M * is_transition_dn,
                r_down[t+1] - r_down[t] <= M * is_transition_dn,
            ])

    da_energy_cost = cp.sum(cp.multiply(da_prices, p_DA)) * dt
    expected_recourse_cost = 0.0
    weighted_psi_sum = 0.0

    # Loop 1: Physical Polytopes (K)
    for k, sc in enumerate(scenarios):
        gamma_x        = sc["gamma_agg_x"]       
        gamma_diag_x   = sc["gamma_agg_diag_x"]  
        h_0_k          = sc["h_0"]               
        pi_k           = sc["probability"]     # Polytope scenario probability
        Gamma_diag_mat = np.diag(gamma_diag_x)  

        # Loop 2: Paired (Up, Down) Scenarios (S)
        for s in range(S):
            w_s = scenario_weights[s]
            joint_prob = pi_k * w_s  # Joint probability of polytope k and market scenario s

            constraints.append(
                p_ch[k, s, :] == p_DA 
                                 + cp.multiply(delta_dn_st[s, :], r_down) 
                                 - cp.multiply(delta_up_st[s, :], r_up) 
                                 + s_plus[k, s, :] - s_minus[k, s, :]
            )

            x_ch_ks = gamma_x + Gamma_diag_mat @ x_0[k, s, :]
            constraints.append(p_ch[k, s, :] == L_inv @ x_ch_ks)
            constraints.append(H_tilde @ x_0[k, s, :] <= h_0_k)

            # Slack Penalty Cost for Scenario Pair (k, s)
            slack_penalty = C_slack * cp.sum(s_plus[k, s, :] + s_minus[k, s, :]) * dt
            
            # Activation Revenues and Costs
            dn_activation_cost = cp.sum(cp.multiply(p_dn_net, cp.multiply(delta_dn_st[s, :], r_down))) * dt
            up_activation_rev  = cp.sum(cp.multiply(p_up_net, cp.multiply(delta_up_st[s, :], r_up))) * dt

            ks_cost = slack_penalty + dn_activation_cost - up_activation_rev
            expected_recourse_cost += joint_prob * ks_cost

            # CVaR linear constraints specifically on slack violation penalty cost
            constraints.append(psi_slack[k, s] >= slack_penalty - zeta_slack)
            weighted_psi_sum += joint_prob * psi_slack[k, s]

    # Formula for CVaR on Slack Variables using joint scenario weights
    cvar_slack_expression = zeta_slack + (1.0 / (1.0 - alpha)) * weighted_psi_sum

    # Constrain the CVaR of slack penalties below maximum allowable threshold
    constraints.append(cvar_slack_expression <= cvar_max)

    total_expected_cost = da_energy_cost + expected_recourse_cost
    problem = cp.Problem(cp.Minimize(total_expected_cost), constraints)
    
    highs_options = {
        'mip_rel_gap': 0.01,
        'primal_feasibility_tolerance': 1e-3,
        'time_limit': float(time_limit_sec)
    }

    print("=" * 85)
    print(f"  RUNNING SOLVER ({K} Polytopes x {S} Paired Scenarios = {K*S} Total Joint Scenarios)")
    print("=" * 85)

    try:
        problem.solve(
            solver=cp.HIGHS, 
            verbose=True, 
            highs_options=highs_options
        )
    except Exception as e:
        print(f"\n[WARNING] Solver interrupted or threw exception: {e}")

    print("\n" + "=" * 85)
    
    has_incumbent = p_DA.value is not None

    if problem.status == cp.OPTIMAL:
        print("  SOLVER STATUS: OPTIMAL (Target MIP Gap Reached)")
    elif problem.status in [cp.USER_LIMIT, cp.OPTIMAL_INACCURATE] or has_incumbent:
        print(f"  SOLVER STATUS: {problem.status} (USING FEASIBLE INCUMBENT SOLUTION)")
    else:
        print(f"  [ERROR] Optimization failed with status '{problem.status}' and no incumbent solution was found.")
        return

    # ---------------------------------------------------------------------------
    # Summary Metrics Output
    # ---------------------------------------------------------------------------
    print("=" * 85)
    print("  EXPECTED COST & SLACK CVAR SUMMARY")
    print("=" * 85)
    print(f"  Day-Ahead Baseline Energy Cost : ${da_energy_cost.value:10.2f}")
    print(f"  Expected Recourse Cost         : ${expected_recourse_cost.value:10.2f}")
    print(f"  Total Expected Net Cost        : ${total_expected_cost.value:10.2f}")
    print("-" * 85)
    print(f"  Slack VaR (ζ_slack)            : ${zeta_slack.value:10.2f}")
    print(f"  Slack CVaR ({int(alpha*100)}%)             : ${cvar_slack_expression.value:10.2f} (Max Limit: ${cvar_max:.2f})")
    print("=" * 85 + "\n")

    # ---------------------------------------------------------------------------
    # Save Outputs (.npy for Plotting Pipeline + .csv for Inspection)
    # ---------------------------------------------------------------------------
    os.makedirs(output_dir, exist_ok=True)

    np.save(os.path.join(output_dir, "p_DA.npy"), p_DA.value)
    np.save(os.path.join(output_dir, "r_up.npy"), r_up.value)
    np.save(os.path.join(output_dir, "r_down.npy"), r_down.value)

    csv_filename = os.path.join(output_dir, "bidding_schedule.csv")

    print("  OPTIMIZED DAY-AHEAD BASELINE & ANCILLARY SERVICE OFFERS")
    print("=" * 85)
    print(f"{'Period':<7} | {'Hour':<6} | {'DA Base (kW)':<12} | {'Market':<10} | {'Action':<8} | {'Up Bid (kW)':<11} | {'Down Bid (kW)':<11}")
    print("-" * 85)

    schedule_data = []

    for t in range(T):
        hour_val = t * dt
        hour_str = f"{int(hour_val):02d}:{int((hour_val % 1) * 60):02d}"

        if u_up.value[t] > 0.5:
            mkt = "UPWARD"
            action = "START" if v_up_start.value[t] > 0.5 else ("END" if v_up_end.value[t] > 0.5 else "HOLD")
        elif u_dn.value[t] > 0.5:
            mkt = "DOWNWARD"
            action = "START" if v_dn_start.value[t] > 0.5 else ("END" if v_dn_end.value[t] > 0.5 else "HOLD")
        else:
            mkt = "IDLE"
            action = "-"
            
        period_str = f"Q-{t:02d}"
        da_val = p_DA.value[t]
        up_bid_val = r_up.value[t]
        down_bid_val = r_down.value[t]

        print(f"{period_str:<7} | {hour_str:<6} | {da_val:12.2f} | {mkt:<10} | {action:<8} | "
              f"{up_bid_val:11.2f} | {down_bid_val:11.2f}")

        schedule_data.append({
            "Period": period_str,
            "Hour": hour_str,
            "DA_Base_kW": da_val,
            "Market": mkt,
            "Action": action,
            "Up_Bid_kW": up_bid_val,
            "Down_Bid_kW": down_bid_val
        })

    fieldnames = ["Period", "Hour", "DA_Base_kW", "Market", "Action", "Up_Bid_kW", "Down_Bid_kW"]
    with open(csv_filename, mode="w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(schedule_data)

    print("-" * 85)

    # ---------------------------------------------------------------------------
    # Revenue, Cost & Risk Analysis Output
    # ---------------------------------------------------------------------------
    r_up_sol = r_up.value
    r_down_sol = r_down.value

    avg_delta_up = np.sum(delta_up_st * scenario_weights[:, None], axis=0)
    avg_delta_dn = np.sum(delta_dn_st * scenario_weights[:, None], axis=0)

    # 1. Stochastic Expected Values
    exp_rev_up_t  = p_up_net * (r_up_sol * avg_delta_up) * dt
    exp_cost_dn_t = p_dn_net * (r_down_sol * avg_delta_dn) * dt

    total_exp_rev_up  = np.sum(exp_rev_up_t)
    total_exp_cost_dn = np.sum(exp_cost_dn_t)

    # 2. Maximum Deterministic Values (Assuming 100% dispatch)
    full_rev_up_t  = p_up_net * r_up_sol * dt
    full_cost_dn_t = p_dn_net * r_down_sol * dt

    total_full_rev_up  = np.sum(full_rev_up_t)
    total_full_cost_dn = np.sum(full_cost_dn_t)

    # Values for financial summary output
    cvar_val = cvar_slack_expression.value if cvar_slack_expression.value is not None else 0.0
    var_val = zeta_slack.value if zeta_slack.value is not None else 0.0

    print("  ANCILLARY SERVICE FINANCIAL & RISK SUMMARY")
    print("=" * 85)
    print("  1. EXPECTED STOCHASTIC VALUES (Based on weighted paired activation profiles)")
    print(f"     - Expected UP Activation Revenue  : ${total_exp_rev_up:10.2f}")
    print(f"     - Expected DOWN Activation Cost   : ${total_exp_cost_dn:10.2f}")
    print("-" * 85)
    print("  2. MAXIMUM VALUES (Assuming 100% Acceptance/Dispatch)")
    print(f"     - 100% Accepted UP Revenue        : ${total_full_rev_up:10.2f}")
    print(f"     - 100% Accepted DOWN Cost         : ${total_full_cost_dn:10.2f}")
    print("-" * 85)
    print("  3. OPERATIONAL SLACK RISK METRICS")
    print(f"     - Slack VaR ({int(alpha*100)}%)                    : ${var_val:10.2f}")
    print(f"     - Slack CVaR ({int(alpha*100)}%)                   : ${cvar_val:10.2f} (Max Limit: ${cvar_max:.2f})")
    print("=" * 85 + "\n")

    print(f"  [INFO] Files exported to folder '{output_dir}/':")
    print(f"         - p_DA.npy, r_up.npy, r_down.npy")
    print(f"         - bidding_schedule.csv")
    print("=" * 85 + "\n")


if __name__ == "__main__":
    solve_expected_cost_bidder(
        input_root="reduced_fleet_scenarios",
        down_data_folder="copula_scenarios",
        output_dir="copula_bids",
        alpha=0.95,
        cvar_max=100,
        time_limit_sec=200.0
    )